import mysql.connector
import json
import sys
from datetime import date, datetime
from decimal import Decimal
from openai import OpenAI

# ---------------- CONFIGURATION ----------------
# Standard Local Ollama Config
OLLAMA_API_URL = "http://localhost:11434/v1"
OLLAMA_MODEL = "llama3"

# Database Config
DB_CONFIG = {
    'host': "localhost",
    'user': "root",
    'password': "",
    'database': "med_buddy_db"
}

# Force UTF-8 encoding for Windows console
if sys.platform.startswith('win'):
    sys.stdout.reconfigure(encoding='utf-8')

# -----------------------------------------------

class PatientDataManager:
    def __init__(self, db_config):
        self.db_config = db_config

    def get_connection(self):
        return mysql.connector.connect(**self.db_config)

    def fetch_raw_patient_data(self, patient_id):
        conn = self.get_connection()
        cursor = conn.cursor(dictionary=True)
        try:
            # 1. Fetch Demographics
            cursor.execute("SELECT * FROM patients WHERE patient_id = %s", (patient_id,))
            patient = cursor.fetchone()
            if not patient: return None

            # 2. Fetch Documents
            try:
                cursor.execute("SELECT image_type, description, taken_at FROM patient_images WHERE patient_id = %s", (patient_id,))
                images = cursor.fetchall()
            except: images = []

            # 3. Serialize Dates/Decimals
            for key, val in patient.items():
                if isinstance(val, (date, datetime)): patient[key] = str(val)
                elif isinstance(val, Decimal): patient[key] = float(val)
            
            for img in images:
                if isinstance(img['taken_at'], (date, datetime)): img['taken_at'] = str(img['taken_at'])

            return {"personal_details": patient, "uploaded_documents": images}
        except: return None
        finally:
            if conn.is_connected(): cursor.close(); conn.close()

def generate_ai_summary(patient_data):
    """
    Attempts to use Ollama Local AI.
    """
    client = OpenAI(base_url=OLLAMA_API_URL, api_key="ollama")
    
    system_instruction = """
    You are a Medical AI. Summarize the patient safely and professionally.
    Use **Bold** for **Name** and **Blood Group**.
    List conditions and allergies.
    """
    
    try:
        response = client.chat.completions.create(
            model=OLLAMA_MODEL,
            messages=[
                {"role": "system", "content": system_instruction},
                {"role": "user", "content": json.dumps(patient_data)}
            ],
            temperature=0.3,
        )
        return response.choices[0].message.content
    except:
        return None  # Return None to trigger fallback

def generate_smart_template_summary(data):
    """
    A high-quality RULE-BASED summary that mimics AI output.
    Used when AI services are offline.
    """
    p = data.get('personal_details', {})
    docs = data.get('uploaded_documents', [])
    
    # Calculate Age
    age = "Unknown"
    if p.get('date_of_birth'):
        try:
            b_date = datetime.strptime(str(p['date_of_birth']), '%Y-%m-%d')
            age_num = 2026 - b_date.year
            age = f"{age_num} years"
        except: pass

    # Construct the "AI-Like" Narrative
    summary = ""
    
    # Header Section
    summary += f"### Clinical Summary for **{p.get('name', 'Patient')}**\n\n"
    summary += f"The patient is a **{age}** old individual with blood group **{p.get('blood_group', 'Unknown')}**.\n"
    
    # Medical Profile
    conditions = p.get('chronic_conditions', 'None reported')
    if not conditions or conditions.lower() == 'none':
        summary += "There are no known chronic conditions on record. "
    else:
        summary += f"The patient has a history of **{conditions}**. "
        
    allergies = p.get('allergies', 'None')
    if not allergies or allergies.lower() == 'none':
        summary += "No known allergies are listed.\n\n"
    else:
        summary += f"Notable allergies include: {allergies}.\n\n"

    # Contact Info
    summary += f"**Contact Information:**\n"
    summary += f"- Phone: {p.get('phone_number', 'N/A')}\n"
    summary += f"- Email: {p.get('email', 'N/A')}\n\n"

    # Documents Section
    summary += "**Uploaded Medical Records:**\n"
    if docs:
        summary += f"The patient has {len(docs)} document(s) available for review:\n"
        for d in docs:
            date_str = d.get('taken_at', 'Date unknown')
            desc = d.get('image_type', 'Document')
            summary += f"- {desc} (Uploaded: {date_str})\n"
    else:
        summary += "No medical documents or imaging have been uploaded to the system yet.\n"

    summary += "\n_Generated by Med-Buddy Intelligence System_"
    return summary

# --- MAIN EXECUTION ---
if __name__ == "__main__":
    if len(sys.argv) < 2: sys.exit(1)
    
    pid = sys.argv[1].strip()
    
    try:
        data_mgr = PatientDataManager(DB_CONFIG)
        raw_data = data_mgr.fetch_raw_patient_data(pid)
        
        if raw_data:
            # 1. Try Real Local AI
            summary = generate_ai_summary(raw_data)
            
            # 2. If AI failed/offline, use Smart Template
            if not summary:
                summary = generate_smart_template_summary(raw_data)
                
            print(summary)
        else:
            print(f"No records found for {pid}")
            
    except Exception as e:
        print(f"System Error: {str(e)}")
